ALTER TABLE `Category`
  ADD COLUMN `seoEnabled` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN `seoTitle` VARCHAR(70) NULL,
  ADD COLUMN `seoDescription` VARCHAR(170) NULL,
  ADD COLUMN `seoIntro` TEXT NULL;

ALTER TABLE `ProductGroup`
  ADD COLUMN `brand` VARCHAR(120) NULL;

ALTER TABLE `Product`
  ADD COLUMN `brand` VARCHAR(120) NULL,
  ADD COLUMN `gtin` VARCHAR(14) NULL,
  ADD COLUMN `mpn` VARCHAR(70) NULL,
  ADD COLUMN `hasNoProductIdentifier` BOOLEAN NOT NULL DEFAULT FALSE;
